feat: add style and bug
Solid-Academy/solid-zillow pull request #15
Opened 2022-10-07 17:38 UTC by Turdubaevajazgul

Issue #:
[Trello](https://trello.com/b/uAKK4mwb/solid-zillow)

## PR type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Screenshots

#### before:

#### after:

## Does this introduce a breaking change?

- [ ] Yes (please describe):
- [ ] No

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Accessibility support has been tested
- [ ] Responsive layout and functionality have been tested
  - [ ] desktop and mobile view responsiveness are supported
  - [ ] no loss of functionality or content when zoomed in to 400%
  - [ ] no horizontal scrolling when zoomed in to 400% (only vertical scrolling, exception: DataGrids)
- [ ] avoids using many levels of prop drilling
- [ ] check console on errors and warnings.
---

References:
- [Clean code](https://github.com/airbnb/javascript)

2022-10-13 00:49 UTC, Bezymeys commented
где скриншот?

2022-10-13 00:57 UTC, Bezymeys requested changes

2022-10-13 00:57 UTC, Bezymeys commented on src/components/card/Card.module.scss
> +@media(max-width:1030px) {
![image](https://user-images.githubusercontent.com/100524271/195474333-613b9d14-dbdf-4fca-bdee-083ac156132a.png)
не верная адаптивка

2022-10-13 00:57 UTC, Bezymeys commented on src/components/card/Card.module.scss
> +.container {
![image](https://user-images.githubusercontent.com/100524271/195474415-f890abb8-ef0d-403e-8309-ae788da783d6.png)
почему у контейнера ширина 100%?
они должны располагаться в середине

2022-10-14 15:27 UTC, asylbekovkairat commented on src/components/card/CardLinks.jsx
> +    <div>
пустые дивы удаляем, тут вместо дива напишите реакт фрагмент

2022-10-14 15:28 UTC, asylbekovkairat commented on src/components/dashboard/Dashboard.jsx
>        <div>Dashboard</div>
текста не пишем в тег div, для текстов есть свои специальные теги: p, h1, span

2022-10-18 16:38 UTC, Improove3567 approved these changes
LGTM!

2022-10-20 15:57 UTC, merged