feat/finished slider
Solid-Academy/solid-zillow pull request #16
Opened 2022-10-08 10:54 UTC by Amas9nine

Issue #:
[Trello](https://trello.com/c/6tknIq9U/15-slider-block-adaptive)

## PR type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [X] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Screenshots

#### before:

#### after:

## Does this introduce a breaking change?

- [ ] Yes (please describe):
- [X] No

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Accessibility support has been tested
- [ ] Responsive layout and functionality have been tested
  - [ ] desktop and mobile view responsiveness are supported
  - [ ] no loss of functionality or content when zoomed in to 400%
  - [ ] no horizontal scrolling when zoomed in to 400% (only vertical scrolling, exception: DataGrids)
- [ ] avoids using many levels of prop drilling
- [ ] check console on errors and warnings.
---

References:
- [Clean code](https://github.com/airbnb/javascript)

2022-10-10 18:50 UTC, Bezymeys commented
добавь контейнер, почему слайдер прокручивается на половину?

2022-10-10 19:08 UTC, Bezymeys requested changes

2022-10-10 19:08 UTC, Bezymeys commented on src/components/carousel/SampleNextArrow.jsx
> +import scss from "./arrow.module.scss";
предлагаю не создавать много файлов и написать это в основном файле компонента

2022-10-10 19:08 UTC, Bezymeys commented on src/components/carousel/SamplePrevArrow.jsx
> +import scss from "./arrow.module.scss";
тоже самое

2022-10-10 19:08 UTC, Bezymeys commented on src/components/carousel/SliderCard.jsx
> +      <div id={scss.square} className={scss.wrapper}>
где кнопка избранное

2022-10-10 19:08 UTC, Bezymeys commented on src/components/carousel/SliderCard.jsx
> +          <div>{description}</div>
описание разделите на маленькие составляющие
![image](https://user-images.githubusercontent.com/100524271/194935140-be6a8f74-aacb-4a06-a8a5-39d8e5e61128.png)

2022-10-10 19:08 UTC, Bezymeys commented on src/components/carousel/arrow.module.scss
> +  position: absolute;
зачем отдельный файл со стилями?

2022-10-10 19:08 UTC, Bezymeys commented on src/components/carousel/slider.js
> +    description: "5 bds | 3 ba | 1,600 sqft | Active",
разделить на маленькие составляющие
![image](https://user-images.githubusercontent.com/100524271/194935329-a4c7780c-c6fb-4d87-aeb0-9c744f013ed6.png)

2022-10-10 19:08 UTC, Bezymeys commented on src/components/carousel/slider.js
> +const array = [
почему данные не в папке  constant?

2022-10-10 19:08 UTC, Bezymeys commented on src/components/dashboard/Dashboard.jsx
> +import Slider from "react-slick";
это не должно быть здесь

2022-10-10 19:08 UTC, Bezymeys commented on src/components/dashboard/Dashboard.jsx
> +      <div id="container">
создай компонент и импортируй его сюда

2022-10-10 19:08 UTC, Bezymeys commented on src/components/dashboard/Dashboard.jsx
> +    duts: true,
тоже самое

2022-10-10 19:08 UTC, Bezymeys commented on src/routes.js
> +export const PublicRoute = ({ Component }) => {
зачем эти изменения?

2022-10-10 19:08 UTC, Bezymeys commented on src/App.css
> +#next {
не засоряйте глобальные стили, для этого есть модульные стили

2022-10-10 19:10 UTC, Bezymeys commented
постарайся всё уместить в 3 файлах (данные, стили, контент)

2022-10-10 19:12 UTC, Bezymeys requested changes

2022-10-10 19:12 UTC, Bezymeys commented on src/components/dashboard/Dashboard.jsx
> +        <div>
почему это в приватном роутинге?

2022-10-11 07:53 UTC, Amas9nine commented on src/components/carousel/SampleNextArrow.jsx
> +import scss from "./arrow.module.scss";
Сделано ! )

2022-10-11 07:53 UTC, Amas9nine commented on src/components/carousel/SamplePrevArrow.jsx
> +import scss from "./arrow.module.scss";
done

2022-10-11 08:18 UTC, Amas9nine commented on src/components/carousel/arrow.module.scss
> +  position: absolute;
done

2022-10-12 10:17 UTC, asylbekovkairat commented on src/components/aboveFooter/AboveFooter.jsx
> +        //   </div>
удали комменты не нужные!!!

2022-10-12 10:18 UTC, asylbekovkairat commented on src/components/aboveFooter/Test.jsx
> +          {arr.map((el) => (
нужно называть массив правильно, не просто arr или array. Например, если в массиве картинки, то ImagesList и так далее

2022-10-12 10:18 UTC, asylbekovkairat commented on src/components/carousel/SliderCard.jsx
> +  console.log("liked:", liked?.imgLikeT);
удали console.log

2022-10-12 10:19 UTC, asylbekovkairat commented on src/constans/slider.js
> +const array = [
Измени название массива

2022-10-12 10:20 UTC, asylbekovkairat reviewed
Таск не выполнен, потому что после того поставить лайк на карточку и обновить страницу лайки уберутся, сделайте так чтобы после обновления лайки не пропадали

2022-10-12 10:21 UTC, asylbekovkairat commented
реши конфликты

2022-10-12 10:22 UTC, asylbekovkairat commented
также нужен адаптив

2022-10-12 10:22 UTC, asylbekovkairat commented
где скриншоты before и after

2022-10-12 10:43 UTC, Amas9nine commented on src/components/aboveFooter/Test.jsx
> +          {arr.map((el) => (
done

2022-10-12 10:45 UTC, Amas9nine commented on src/components/carousel/SliderCard.jsx
> +  console.log("liked:", liked?.imgLikeT);
done

2022-10-12 10:46 UTC, Amas9nine commented on src/constans/slider.js
> +const array = [
done)

2022-10-12 15:44 UTC, Bezymeys requested changes

2022-10-12 15:44 UTC, Bezymeys commented on src/components/aboveFooter/Test.jsx
> +          {arr.map((el) => (
где done?

2022-10-12 15:44 UTC, Bezymeys commented on src/components/carousel/SliderCard.jsx
> +  console.log("liked:", liked?.imgLikeT);
same

2022-10-12 15:44 UTC, Bezymeys commented on src/constans/slider.js
> +const array = [
same

2022-10-12 15:45 UTC, Bezymeys commented
у тебя конфликты исправляй

2022-10-23 11:16 UTC, Improove3567 commented on src/redux/reducers/slice.js
> +      alert("deleted");
alert не нужен, так как в zillow такого нет, просто лайк становится другим цветом

2022-10-23 11:16 UTC, Improove3567 commented on src/redux/reducers/slice.js
> +      alert("added");
alert не нужен, так как в zillow такого нет, просто лайк становится другим цветом

2022-10-23 11:18 UTC, Improove3567 commented on yarn.lock
> +resize-observer-polyfill@^1.5.0:
Мы не используем эту библиотеку, нужно будет удалить

2022-10-23 11:23 UTC, Improove3567 commented on src/components/carousel/SampleNextArrow.jsx
> +  const { onClick } = props;
вы можете сразу этот props принимать " function SampleNextArrow({onClick}), не нужно создавать константу, и поменяйте название пропса(более подробнее), название onClick не пойдет

2022-10-23 11:27 UTC, Amas9nine commented on src/redux/reducers/slice.js
> +      alert("deleted");
done

2022-10-23 11:27 UTC, Amas9nine commented on src/redux/reducers/slice.js
> +      alert("added");
done

2022-10-23 11:28 UTC, Amas9nine commented on yarn.lock
> +resize-observer-polyfill@^1.5.0:
done

2022-10-23 11:36 UTC, Amas9nine commented on src/components/carousel/SampleNextArrow.jsx
> +  const { onClick } = props;
done

2022-10-23 18:36 UTC, Improove3567 commented
the layout isnt the same, you have to improve

2022-10-24 09:40 UTC, asylbekovkairat commented on src/App.css
> +#prev {
id для стилей не используем

2022-10-24 09:40 UTC, asylbekovkairat commented on src/components/carousel/SampleNextArrow.jsx
> +        <img id="arrL" className={scss.arrowL} src="imegs/skip.png" alt="imgicoins" />
исправьте название папки с "imegs" на "images"

2022-10-24 09:41 UTC, asylbekovkairat commented on src/components/carousel/SampleNextArrow.jsx
> +        <img id="arrL" className={scss.arrowL} src="imegs/skip.png" alt="imgicoins" />
неправильно задаете классы, нужно их называть правильно чтобы было понятно

2022-10-24 09:41 UTC, asylbekovkairat commented on src/components/carousel/SamplePrevArrow.jsx
> +        <img id="arrR" className={scss.arrowR} src="imegs/previous.png" alt="LikesPigS" />
не arrowR, а arrowRight

2022-10-24 09:42 UTC, asylbekovkairat commented on src/components/carousel/SliderCard.jsx
> +      <div>
удалите этот пустой див, если он нигде не используется

2022-10-24 09:43 UTC, asylbekovkairat commented on src/components/carousel/SliderHead.jsx
> +        <p className={scss.p}>Based on homes you recently viewed</p>
изучите методологию БЭМ

2022-10-24 09:48 UTC, Amas9nine commented on src/components/carousel/SliderHead.jsx
> +        <p className={scss.p}>Based on homes you recently viewed</p>
ok

2022-10-24 09:48 UTC, Improove3567 commented
I can't approve because the layout doesn't same the original

2022-10-24 09:50 UTC, Amas9nine commented on src/components/carousel/SliderCard.jsx
> +      <div>
done

2022-10-24 09:54 UTC, Amas9nine commented on src/components/carousel/SamplePrevArrow.jsx
> +        <img id="arrR" className={scss.arrowR} src="imegs/previous.png" alt="LikesPigS" />
done

2022-10-24 10:25 UTC, Amas9nine commented on src/components/carousel/SampleNextArrow.jsx
> +        <img id="arrL" className={scss.arrowL} src="imegs/skip.png" alt="imgicoins" />
done

2022-10-24 10:31 UTC, Amas9nine commented on src/components/carousel/SampleNextArrow.jsx
> +        <img id="arrL" className={scss.arrowL} src="imegs/skip.png" alt="imgicoins" />
done

2022-10-25 12:18 UTC, Improove3567 commented
I cant, approve, layout isnt the same with original.

2022-10-25 12:24 UTC, Improove3567 commented
Slider buttons must be hafl transparent

2022-10-25 12:25 UTC, Improove3567 commented
You have to center top texts and slider

2022-10-25 12:26 UTC, Improove3567 commented
do slider  smaller

2022-10-25 12:26 UTC, Improove3567 commented
change background inactive likes

2022-10-25 15:44 UTC, Improove3567 commented on src/components/carousel/SampleNextArrow.jsx
> +function SampleNextArrow({ onClick }) {
Измените название функции которую получаете из пропсов "onClick" не пойдет

2022-10-25 15:44 UTC, Improove3567 commented on src/components/carousel/SampleNextArrow.jsx
> +      <div className="left" onClick={onClick}>
Измените название функции которую получаете из пропсов "onClick" не пойдет

2022-10-25 15:45 UTC, Improove3567 commented on src/components/carousel/SamplePrevArrow.jsx
> +    <>
уберите react фрагмент

2022-10-25 15:46 UTC, Improove3567 commented on src/components/home/HomePage.jsx
>      <>
уберите react фрагмент

2022-10-25 16:36 UTC, Amas9nine commented on src/components/home/HomePage.jsx
>      <>
done

2022-10-25 16:36 UTC, Amas9nine commented on src/components/carousel/SamplePrevArrow.jsx
> +    <>
done

2022-10-25 16:36 UTC, Amas9nine commented on src/components/carousel/SampleNextArrow.jsx
> +function SampleNextArrow({ onClick }) {
done

2022-10-26 16:16 UTC, Improove3567 commented on src/components/carousel/SamplePrevArrow.jsx
> +      <img id="rightArray" className={scss.arrowRight} src="images/previous.png" alt="LikesPigS" />
У вас alt не правильный, нужно такое название чтобы было понятно что это, если картинка не прогрузится, например просто like

2022-10-26 16:16 UTC, Improove3567 commented on src/components/carousel/SliderCard.jsx
> +        <img className={scss.imgLike} src={isLiked ? imgLikeT : imgLike} alt="likePigS" />
У вас alt не правильный, нужно такое название чтобы было понятно что это, если картинка не прогрузится, например просто like

2022-10-26 16:16 UTC, Improove3567 commented on src/components/carousel/SliderCard.jsx
> +        <img className={scss.imgSlider} src={img} key={id} alt="pig" />
У вас alt не правильный, нужно такое название чтобы было понятно что это, если картинка не прогрузится, например просто like

2022-10-26 17:12 UTC, Improove3567 commented on src/components/card/Card.jsx
> +                    <img className={css.homeImg} src={element.img} alt="img" />
img не пойдет, название alt должна обьяснять картинку,  homeImg хотябы нужно

2022-10-26 17:13 UTC, AiteginJyldyzbekov commented on src/components/carousel/SliderCard.jsx
> +        <img className={scss.imgLike} src={isLiked ? imgLikeT : imgLike} alt="likes" />
поставьте like

2022-10-26 17:41 UTC, Improove3567 approved these changes
LGTM!

2022-10-26 17:44 UTC, merged