Feat/footer
Solid-Academy/solid-zillow pull request #19
Opened 2022-10-10 13:26 UTC by aiskairr

Issue #:
[Trello](https://trello.com/c/aXSGh5Y6/5-footer-adaptive)

## PR type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Screenshots

#### before:

#### after:

## Does this introduce a breaking change?

- [x] Yes (please describe):
- [ ] No

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Accessibility support has been tested
- [ ] Responsive layout and functionality have been tested
  - [x] desktop and mobile view responsiveness are supported
  - [ ] no loss of functionality or content when zoomed in to 400%
  - [x] no horizontal scrolling when zoomed in to 400% (only vertical scrolling, exception: DataGrids)
- [ ] avoids using many levels of prop drilling
- [x] check console on errors and warnings.
---

References:
- [Clean code](https://github.com/airbnb/javascript)

2022-10-10 16:21 UTC, Bezymeys commented
please add screenshot

2022-10-10 16:41 UTC, Bezymeys commented
please make gaps smaller

2022-10-10 16:43 UTC, Bezymeys requested changes

2022-10-10 16:43 UTC, Bezymeys commented on src/components/footer/Footer.jsx
> +                <img src="./images/footer/Facebook_Logo_(2019).png" alt="" />
wrap them link

2022-10-10 16:43 UTC, Bezymeys commented on src/components/footer/Footer.jsx
> +              <img src="./images/footer/appstorebadgeenwhite-2x.png" alt="apple" />
same

2022-10-10 16:43 UTC, Bezymeys commented on src/components/footer/Footer.jsx
> +              <img src="./images/footer/z-logo-default.svg" alt="z-logo" />
same

2022-10-10 16:43 UTC, Bezymeys commented on src/components/footer/Footer.jsx
> +              <p>{t("footer.ContactZillow")}</p>
change to constantZillow with small (C)

2022-10-10 17:35 UTC, Bezymeys requested changes

2022-10-10 17:35 UTC, Bezymeys commented on src/components/footer/Footer.jsx
> +            <Link to="#">{t("footer.informatio")}</Link>
change style link

2022-10-10 17:35 UTC, Bezymeys commented on src/components/footer/Footer.jsx
> +                <LinksCard key={items.id} {...items} />
эта карточка для линков обязателен?

2022-10-10 17:37 UTC, Bezymeys commented
добавь контейнер в App.scss и задай ему ширину в px

2022-10-11 14:48 UTC, aiskairr commented on src/components/footer/Footer.jsx
> +                <LinksCard key={items.id} {...items} />
Да

2022-10-12 14:57 UTC, Bezymeys approved these changes

2022-10-12 14:57 UTC, merged